---
title: "Sometimiento de trabajos"
---

Son bienvenidos todos los trabajos en cuya metodología se haya usado el lenguaje de programación __R__. La forma de presentar los trabajos será por medio de comunicaciones o pósters.

## Pasos
El sometimiento de trabajos se realizará por medio de la herramienta CMT. A continuación los pasos para someter un trabajo.

1. Visitar [este enlace](https://cmt3.research.microsoft.com/User/Login){target="_blank"} para crear una cuenta en CMT. Si ya tiene una cuenta en CMT, continue con el paso siguiente.
1. Abra su cuenta de CMT creada en el paso anterior.
1. Visitar [este enlace](https://cmt3.research.microsoft.com/RDay2025){target="_blank"} para ingresar al sistema de sometimiento de trabajos del R Day en CMT.
1. Dar clic en el botón __Create new submission__.
1. Ingresar el título, el resumen de <span style="color: red;">1000 caracteres</span> y los autores. Toda la información se debe ingresar en <span style="color: red;">INGLÉS</span>.
1. Elegir si es comunicación o póster.
1. Oprimir el botón __Submit__ para someter su trabajo.

Una vez sometido el trabajo usted deberá esperar hasta la fecha de notificación (aceptación o rechazo) de trabajos. Las fechas se encuentran [en este enlace](fechas.html).

Abajo un video ilustrativo de cómo someter un trabajo.

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/otSQNhyvemw?si=FHSdgOnnvIRsGIdP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</center>

<br/>

Con los trabajos aceptados se hará una selección para incluirlos en los "Proceedings of Springer CCIS Book Series". Las dos modalidades para que los trabajos aceptados aparezcan en los Proceedings son:

- Como artículo corto (6 a 10 páginas).
- Como artículo extendido (10 a 16 páginas).

Para conocer todos los detalles de los Proceedings recomendamos visitar [este enlace](call_papers.html) para la versión en español o [este enlace](llamado_trabajos.html) para la versión en inglés.

<br/>

The Microsoft CMT service was used for managing the peer-reviewing process for this conference. This service was provided for free by Microsoft and they bore all expenses, including costs for Azure cloud services as well as for software development and support.
